name: DEPLOYMENT-OF-K3S-ON-AWS-01
description: A minimal AWS Python Pulumi program
runtime:
  name: python
  options:
    toolchain: pip
    virtualenv: venv
config:
  pulumi:tags:
    value:
      pulumi:template: aws-python
